server:
  port: 80

spring:
  application:
    name: zy-gateway
  # \u6570\u636E\u5E93\u914D\u7F6E
  data:
    mongodb:
      host: 192.168.56.129
      port: 27017

# \u914D\u7F6E\u8F93\u51FA\u65E5\u5FD7
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    cn.com.zybank.gateway: DEBUG
    sun.rmi: ERROR
    org.mongodb.driver: ERROR


#\u5F00\u542F\u7AEF\u70B9, \u5F00\u53D1\u5B8C\u6210\u8FD9\u4E2A\u529F\u80FD\u540E\u5C31\u53EF\u4EE5\u6CE8\u91CA\u6389\u4E0B\u9762\u914D\u7F6E\u4E86
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'

