server:
  port: 80

spring:
  application:
    name: zy-gateway
  data:
    mongodb:
      host: 192.168.56.129
      port: 27017
  cloud:
    gateway:
      routes:
        - id: host_route_github
          uri: https://github.com/aaronwong1989
          predicates:
            - Path=/github/{segment}
            - Weight=service1,95
        - id: host_route_github_v2
          uri: https://github.com/aaronwong1989
          predicates:
            - Path=/github/{segment}
            - Weight=service1,5

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    cn.com.zybank.gateway: DEBUG
    sun.rmi: ERROR
    org.mongodb.driver: ERROR

management:
  endpoints:
    web:
      exposure:
        include: ["prometheus"]
      base-path: "/actuator/"