@startuml

header 开发者注册

actor 开发者 as dev
participant 开放平台 as opb

autonumber "<font color=blue><b>"
dev -> opb: 个人和企业开发者注册
dev -> opb: 个人和企业开发者实名认证
dev -> opb: 创建应用
dev -> dev: a.生成密钥对提供公钥\nb.配置前端回调URL\nc.配置后台异步通知URL
dev -> opb: 提交创建应用申请
dev -> opb: 下载开放平台SDK和公钥
dev <- opb: SDK和公钥文件

@enduml